import Head from "next/head";
import Image from "next/image";
import Login from "../components/Login";

export default function Home() {
  return (
    <>
      <Head>
        <title>Scribbes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Login />
      </div>
    </>
  );
}
